apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

namePrefix: staging-

replicas:
  - name: guestbook-ui
    count: 2

commonLabels:
  environment: staging
