{{- if .Values.database.enableMigration }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "guestbook-chart.fullname" . }}-db-migration
  labels:
    {{- include "guestbook-chart.labels" . | nindent 4 }}
  annotations:
    # Helm Hook 注解 - 关键!
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ include "guestbook-chart.fullname" . }}-db-migration
    spec:
      restartPolicy: Never
      containers:
      - name: db-migration
        image: "{{ .Values.database.migrationImage }}"
        command:
          - sh
          - -c
          - |
            echo "Running database migration for {{ .Values.environment }} environment..."
            sleep 5
            echo "Migration completed successfully!"
            # 实际场景中这里会执行真正的迁移脚本
            # 例如: flyway migrate 或 liquibase update
      {{- if .Values.database.secretName }}
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.secretName }}
              key: password
      {{- end }}
{{- end }}
