replicaCount: 1

image:
  repository: nginx
  tag: "1.27-alpine"

service:
  type: ClusterIP
  port: 80

# Redis 依赖配置
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: false  # 学习环境禁用持久化
