apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-dev
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/djx339/argocd-demo-01
    targetRevision: HEAD
    path: helm-charts/webapp
    helm:
      values: |
        replicaCount: 1
        redis:
          enabled: true
          master:
            persistence:
              enabled: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp-dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
