replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.27-alpine"

service:
  type: ClusterIP
  port: 80

resources: {}

environment: default

ingress:
  enabled: false

database:
  enableMigration: false
  migrationImage: "busybox:1.36"
  secretName: ""
